export const rankingCss=`
.daily-preview{margin-bottom:48px}.preview-note{border:1px solid #3b506b;background:#102038;padding:14px 18px;color:#bccbe0;font-size:13px;display:flex;justify-content:space-between;gap:20px}.preview-note a{white-space:nowrap}.daily-heading{padding:32px 0 24px}.daily-heading h2{font-size:34px;line-height:1.3;letter-spacing:-.025em;margin:0 0 12px}.daily-heading p{margin:0;color:var(--muted);font-size:15px}.daily-meta{display:flex;justify-content:space-between;align-items:center;margin-top:18px;font:12px ui-monospace,monospace;color:var(--muted)}.daily-meta a{color:var(--muted)}.innovation-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:20px;list-style:none;margin:0;padding:0}.innovation-card{min-width:0;border:1px solid #354b65;background:#0d1b30;display:flex;flex-direction:column}.innovation-photo{display:block;width:100%;height:auto;aspect-ratio:16/9;object-fit:cover}.innovation-body{padding:18px;flex:1;display:flex;flex-direction:column}.rank-category{font:11px ui-monospace,monospace;color:#9eb3ce}.innovation-card h3{font-size:17px;line-height:1.55;margin:12px 0 12px;overflow-wrap:anywhere;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden}.innovation-card h3 a{text-decoration:none}.innovation-card h3 a:hover{color:var(--acid)}.innovation-card p{margin:0 0 20px;font-size:13px;color:var(--muted);display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden}.innovation-source{margin-top:auto;padding-top:14px;border-top:1px solid var(--line);color:#8a9bb1;font-size:11px;line-height:1.8}.innovation-source span{color:#75859a}.preview-rules{border-bottom:1px solid var(--line);padding:20px 0;margin-top:8px;color:var(--muted);font-size:13px}.preview-rules summary{cursor:pointer;color:#b5c5dc}.preview-rules p{max-width:80ch;margin:16px 0}
@media(max-width:1000px){.innovation-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.preview-note{display:block}.preview-note a{display:block;margin-top:8px}.daily-heading h2{font-size:27px}.innovation-grid{grid-template-columns:1fr}.innovation-photo{max-height:220px}.daily-preview{margin-bottom:32px}}
`;
import { existsSync } from 'node:fs';
import type { RankedItem } from './maker-ranking-rules.ts';
type Entry=RankedItem & {rankingScore:number;rankingReason:string};
const escape=(value:string)=>value.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function rankingSection(ranking:{date:string;items:Entry[]}|null, current:RankedItem[]) {
  if(!ranking)return {html:'',css:''};
  const items=ranking.items.filter(i=>current.some(c=>c.url===i.url)&&!!i.cover?.match(/^assets\/covers\/[a-f0-9]+\.webp$/)&&existsSync('pages-preview/'+i.cover)).slice(0,8);
  const labels:Record<string,string>={hardware:'AI 与硬件','ai-products':'AI与设计',industry:'AI创新案例',tip:'AI教育实践'};
  const cards=items.map((i,index)=>{
    const url=new URL(i.url);if(!['http:','https:'].includes(url.protocol))throw Error('Invalid ranking URL');
    return `<li class="innovation-card"><img class="innovation-photo" src="${escape(i.cover!)}" alt="${escape(i.title)}" loading="lazy" width="960" height="540"><div class="innovation-body"><span class="rank-category">TOP ${String(index+1).padStart(2,'0')} · ${escape(labels[i.category]||'AI创新')}</span><h3><a href="${escape(url.href)}" target="_blank" rel="noopener noreferrer">${escape(i.title)}</a></h3><p>${escape(i.summary)}</p><div class="innovation-source">${escape(i.sourceName||'原文来源')}<br><span>AI 推荐 · ${i.rankingScore} 分</span></div></div></li>`;
  }).join('');
  return {css:rankingCss,html:`<section class="daily-preview" aria-label="AI创新每日top排行榜"><div class="daily-heading"><h2>AI创新每日top排行榜</h2><p>发现值得尝试的 AI 应用、智能硬件、创新设计与教育实践。</p><div class="daily-meta"><span>${escape(ranking.date)} · 北京时间 · 最多 8 篇</span><a href="#ranking-rules">评价规则 ↓</a></div></div><ol class="innovation-grid">${cards}</ol>${items.length?'':'<p class="empty">本期暂无符合入选规则的内容。</p>'}<details id="ranking-rules" class="preview-rules"><summary>榜单如何选择？</summary><p>创新性 35%、AI 相关性 30%、实践价值 20%、启发与教育价值 10%、证据与可信度 5%。AI 根据当前已公开资讯的标题与摘要评价，每日更新；评分代表本站推荐标准。入选必须有真实缩略图，排除纯广告、重复消息与空泛宣传，内容不足时不凑数。70 分为首版试用门槛，后续根据实际内容校准。</p></details></section>`};
}
