// 生成独立静态预览：真实首版人工整理内容，不包含密钥或运行数据库。
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
const { items, updatedAt } = JSON.parse(readFileSync("pages-preview/data.json", "utf8"));
const payload = JSON.stringify(items).replaceAll("<", "\\u003c");
mkdirSync("pages-preview", { recursive: true });
writeFileSync("pages-preview/index.html", `<!doctype html>
<html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AI maker. 创新中心</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f8f9f8;color:#1e2c33;font-family:system-ui,-apple-system,"PingFang SC",sans-serif;line-height:1.7}header,main,footer{max-width:1000px;margin:auto;padding:28px 24px}header{border-bottom:1px solid #dde4e4}h1{font-size:30px;margin:0}header p{margin:8px 0;color:#52676c}.notice{font-size:14px;color:#52676c}nav{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}button,input{font:inherit;border:1px solid #ccd6d7;border-radius:8px;padding:8px 14px;background:white;color:inherit}button{cursor:pointer}button[aria-pressed=true]{background:#166d78;color:white;border-color:#166d78}input{width:100%;margin-bottom:16px}article{background:white;border:1px solid #dde4e4;border-radius:12px;padding:24px;margin:16px 0}h2{font-size:21px;line-height:1.5;margin:8px 0}article p{color:#52676c}a{color:#166d78;text-underline-offset:3px}.meta,.reason,footer{font-size:14px}.reason{border-top:1px solid #e2e8e8;padding-top:12px}.empty{padding:40px 0}button:focus-visible,a:focus-visible,input:focus-visible{outline:3px solid #166d78;outline-offset:3px}@media(max-width:600px){header,main,footer{padding:20px 16px}h1{font-size:25px}article{padding:18px}}</style>
<header><h1>AI maker. 创新中心</h1><p>设计工具 · 创新案例 · 教育实践</p><div class="notice">定时采集与 AI 编辑 · 计划每 6 小时更新 · 部分首批内容为人工整理。</div></header>
<main><nav aria-label="栏目筛选"><button data-category="all" aria-pressed="true">全部</button><button data-category="ai-products" aria-pressed="false">设计工具</button><button data-category="industry" aria-pressed="false">创新案例</button><button data-category="tip" aria-pressed="false">教育实践</button></nav><label for="query">搜索标题与摘要</label><input id="query" type="search" placeholder="例如：三维、教学、交互"><p id="count" aria-live="polite"></p><section id="items" aria-label="资讯列表"></section></main>
<footer>基于 <a href="https://github.com/KKKKhazix/AIHOT">AIHOT</a> 开源框架制作。原文版权归各来源所有。最近自动更新：${updatedAt ?? "等待首次运行"}。</footer>
<script>const items=${payload};let category='all';const names={'rss-mit-ai':'MIT News','rss-google-blog':'Google Blog','rss-dezeen':'Dezeen','rss-designboom':'designboom'};const root=document.querySelector('#items');function node(tag,text,cls){const n=document.createElement(tag);n.textContent=text;if(cls)n.className=cls;return n}function render(){const query=document.querySelector('#query').value.trim().toLowerCase();const filtered=items.filter(i=>(category==='all'||i.category===category)&&(i.title+' '+i.summary+' '+i.tags.join(' ')).toLowerCase().includes(query));root.replaceChildren();document.querySelector('#count').textContent=filtered.length+' 条资讯';for(const i of filtered){const a=document.createElement('article');a.append(node('div',i.sourceName||names[i.sourceId]||i.sourceId,'meta'),node('h2',i.title),node('p',i.summary),node('p',(i.origin==='model'?'AI 编辑 · 评分 '+(i.score??'未评分')+' · ':'人工整理 · ')+i.reason,'reason'));const link=node('a','阅读来源原文');link.href=i.url;link.target='_blank';link.rel='noopener noreferrer';a.append(link);root.append(a)}if(!filtered.length)root.append(node('p','没有匹配内容，请尝试其他关键词。','empty'))}document.querySelectorAll('[data-category]').forEach(b=>b.addEventListener('click',()=>{category=b.dataset.category;document.querySelectorAll('[data-category]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));render()}));document.querySelector('#query').addEventListener('input',render);render();</script></html>`);
console.log("静态预览已生成：pages-preview/index.html");
